# 服务器前置任务(ubuntu使用 Centos项目注释或删掉)
- name: seafile
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
    - name: Install Python
      raw: sudo apt update && sudo apt-get -y install python
      ignore_errors: yes
  
# 核心任务

- name: seafile
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - variables.yml

  vars:
    mysql_users: wordpress

  roles:
    - {role: cloud, tags: "cloud"}
    - {role: common, tags: "common"}
    - {role: docker, tags: "docker"}
    - {role: seafile, tags: "seafile"}
    - {role: documentserver, tags: "documentserver"}
    # - {role: end, tags: "end"}
