- name: copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: /data/docker-compose.yml

- name: run docker-compose
  shell: docker-compose up -d 
  args:
    chdir: /data
    
- name: Create soft link
  shell: |
    ln -sf /opt/seafile-data  /data/wwwroot
    ln -sf /opt/seafile-mysql  /data/wwwroot
