#1 install Seafile by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"
 
#2 Run Docker compose
- name: copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: /data/docker-compose.yml

- name: run docker-compose
  shell: |
    docker-compose up -d 
    sleep 30s
  args:
    chdir: /data

- name: Copy OnlyOffice Document Server connection template
  copy: 
    src: onlyoffice.conf
    dest: /data/config
  
#3 UX Settings    
- name: Create soft link
  shell: |
    ln -sf /opt/seafile-data  /data/wwwroot
    ln -sf /opt/seafile-mysql  /data

    
# check service state
- name: Check Seafile Service
  shell: docker ps
  register: check_seafile_service
  notify: check_seafile_service
