#1 install Seafile by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

- name: Get Docker Gateway
  shell: ip route show | grep docker0 | awk '{print $9}'
  register: docker_gateway

- name: Create /data/wwwroot/seafile
  file:
    path: /data/wwwroot/seafile
    state: directory

#2 Run Docker compose
- name: copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: /data/wwwroot/seafile/docker-compose.yml
  
- name: run docker-compose
  shell: |
    docker-compose up -d 
    sleep 30s
  args:
    chdir: /data

- name: Copy OnlyOffice Document Server connection template
  copy: 
    src: onlyoffice.conf
    dest: /data/wwwroot/seafile/config

- name: Create ssl directory for user's CA
  file:
    path: /data/wwwroot/seafile/seafile-data/ssl
    state: directory
  
#3 UX Settings    
- name: Create soft link
  shell: |
    ln -sf /data/wwwroot/seafile/seafile-data  /opt/seafile-data

    
# check service state
- name: Check Seafile Service
  shell: docker ps
  register: check_seafile_service
  notify: check_seafile_service
