#1 install Seafile by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"
 
#2 Run Docker compose
- name: copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: /data/docker-compose.yml

- name: run docker-compose
  shell: docker-compose up -d 
  args:
    chdir: /data

- name: Update seahub_settings.py for OnlyOffice
  blockinfile:
    path: /opt/seafile-data/seafile/conf/seahub_settings.py
    block: |
      # Enable Only Office
      ENABLE_ONLYOFFICE = True
      VERIFY_ONLYOFFICE_CERTIFICATE = False
      ONLYOFFICE_APIJS_URL = 'http://seafile.example.com:9002/web-apps/apps/api/documents/api.js'
      ONLYOFFICE_FILE_EXTENSION = ('doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'odt', 'fodt', 'odp', 'fodp', 'ods', 'fods')
      ONLYOFFICE_EDIT_FILE_EXTENSION = ('docx', 'pptx', 'xlsx')
      PasswordAuthentication no
    
#3 UX Settings    
- name: Create soft link
  shell: |
    ln -sf /opt/seafile-data  /data/wwwroot
    ln -sf /opt/seafile-mysql  /data

    
# check service state
- name: Check Seafile Service
  shell: docker ps
  register: check_seafile_service
  notify: check_seafile_service
