- name: Create volum 
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
  with_items:
    - /data/mysql
    - /data/seafile
    - /data/seafile/ssl

- name: copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: /data/docker-compose.yml
    
- name: run docker-compose
  docker_compose:
    project_src: /data/
  register: output






