# Please don't replace this file directly when Seafile have new version, you should merge it
# add1 restart: always
# add2 phpmyadmin

version: '2.0'
services:
  db:
    image: mariadb:10.1
    container_name: seafile-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD={{seafile_mysql_root_password}}
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/seafile-mysql/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    restart: always
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/seafile-data:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD={{seafile_mysql_root_password}}
      - TIME_ZONE=Asia/Shanghai
      - SEAFILE_ADMIN_EMAIL={{seafile_admin_email}}
      - SEAFILE_ADMIN_PASSWORD={{seafile_admin_password}}
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=seafile.example.com
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net
  
  # add by Websoft9
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "9090:80"
    depends_on:
      - db
    networks:
      - seafile-net
      
networks:
  seafile-net:
