# edit by seafile's offical file
# refer to https://docs.seafile.com/d/cb1d3f97106847abbf31/files/?p=/docker/docker-compose.yml
{% if ansible_os_family  == 'Debian' %}
version: '2.0'
services:
  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    restart: always
    entrypoint: memcached -m 256
          
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/wwwroot/seafile/seafile-data:/shared
    environment:
      - DB_HOST={{docker_gateway.stdout}}
      - DB_ROOT_PASSWD={{seafile_mysql_root_password}}
      - TIME_ZONE=Asia/Shanghai
      - SEAFILE_ADMIN_EMAIL={{seafile_admin_email}}
      - SEAFILE_ADMIN_PASSWORD={{seafile_admin_password}}
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=seafile.example.com
    depends_on:
      - memcached
{% endif %}
{% if ansible_os_family  == 'Debian' %}
{% endif %}
networks:
  default:
    external:
      name: apps
